---
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5).to_i %>
:max_retries: 3

:queues:
- [ critical, 3 ]
- [ default, 2 ]
- [ low, 1 ]

:timeout: 25

# Configure Redis connection
:redis:
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>

# Dead job retention (in seconds, default is 6 months)
:dead_max_jobs: 10000
:dead_timeout_in_seconds: 15552000

# Logging
:verbose: false

# Schedule (for periodic jobs if using sidekiq-cron)
# :schedule:
#   mark_inactive_users_offline:
#     cron: "*/1 * * * *"
#     class: "MarkInactiveUsersOfflineJob"
#     queue: low
